### ISSUE TITLE
Suggest add defcustom `org2elcomment-default-source'

### ISSUE THREAD

**Issue by tumashu** [cute-jumper/org2elcomment#1]

**Comment by cute-jumper** [comment]
This [commit](https://github.com/cute-jumper/org2elcomment/commit/0e2733f2eede71abc4586909aaf49e4deaf2df1e) adds a variable to remember the file name selected last time. Is this what you want to achieve using this `org2elcomment-default-source` variable?

**Comment by tumashu** [comment]
Good job!
